name: CI

on: [pull_request]

jobs:
  test_ubuntu_24_04:
    name: Ubuntu 24.04 / Elixir ${{ matrix.elixir }} / Erlang/OTP ${{ matrix.otp }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.17.1"
            otp: "27.0"
            lint: true
          - elixir: "1.16.3"
            otp: "26.2.5"
          - elixir: "1.15.8"
            otp: "25.3.2.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          version-type: strict
      - name: Restore dependencies cache
        uses: actions/cache@v4
        id: cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-mix-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          MIX_ENV: test
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test --trace
      - if: ${{ matrix.lint }}
        name: Check Format
        run: mix format --check-formatted
